### ISSUE TITLE
Watcher for pods.v1@none has failed

### ISSUE THREAD

**Issue by chevdor** [hardbyte/netchecks#67]
I installed in the default `netchecks` namespace and created an assertion there, it works fine.

Creating an assertion in another namespace (let's call it `ns=foo`) however, the operator pod starting in this namespace fails with:
```
2023-12-20 14:30:04 [debug    ] Setting config from file       config_file_path=PosixPath('/var/config/config.json')
2023-12-20 14:30:04 [debug    ] Starting operator              config={"probe": {"imagePullSecrets": [], "podAnnotations": {}, "image": {"repository": "ghcr.io/hardbyte/netchecks", "pullPolicy": "Always", "tag": "main"}, "resources": {}, "verbose": false}, "metrics": {"port": 9090, "enabled": true}}
/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_core/reactor/running.py:179: FutureWarning: Absence of either namespaces or cluster-wide flag will become an error soon. For now, switching to the cluster-wide mode for backward compatibility.
  warnings.warn("Absence of either namespaces or cluster-wide flag will become an error soon."
[2023-12-20 14:30:04,243] kopf._core.engines.a [INFO    ] Initial authentication has been initiated.
[2023-12-20 14:30:04,246] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2023-12-20 14:30:04,246] kopf._core.engines.a [INFO    ] Initial authentication has finished.
[2023-12-20 14:30:04,310] kopf._core.reactor.o [WARNING ] Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.
[2023-12-20 14:30:04,311] kopf._core.reactor.o [ERROR   ] Watcher for pods.v1@none has failed: ('pods is forbidden: User "system:serviceaccount:foo:netcheck-operator" cannot list resource "pods" in API group "" at the cluster scope', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'pods is forbidden: User "system:serviceaccount:foo:netcheck-operator" cannot list resource "pods" in API group "" at the cluster scope', 'reason': 'Forbidden', 'details': {'kind': 'pods'}, 'code': 403})
Traceback (most recent call last):
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/errors.py", line 148, in check_response
    response.raise_for_status()
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.96.0.1:443/api/v1/pods')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 108, in guard
    await coro
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_core/reactor/queueing.py", line 175, in watcher
    async for raw_event in stream:
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/watching.py", line 86, in infinite_watch
    async for raw_event in stream:
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/watching.py", line 174, in continuous_watch
    objs, resource_version = await fetching.list_objs(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/fetching.py", line 28, in list_objs
    rsp = await api.get(
          ^^^^^^^^^^^^^^
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
               ^^^^^^^^^^^^^^
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/netchecks/bin/.cache/virtualenvs/netcheck-operator-9TtSrW0h-py3.11/lib/python3.11/site-packages/kopf/_cogs/clients/api.py", line 85, in request
    await errors.check_response(response)  # but do not parse it!
```

I can see the service account was created:
```
$ k get serviceaccount -n $ns
NAME                SECRETS   AGE
default             0         50d
netcheck-operator   0         21m
```

**Comment by hardbyte** [comment]
Thanks for the bug report. I might not be able to look into this until after Christmas. 


Did you install via helm? 

One thing to check is whether the system:serviceaccount:foo:netcheck-operator has a cluster role binding to the role I defined in the chart, and if any other time bindings are present.

**Comment by chevdor** [comment]
> Thanks for the bug report. I might not be able to look into this until after Christmas.

no stress, I also need to dig a bit more.

> Did you install via helm?

yes

> One thing to check is whether the system:serviceaccount:foo:netcheck-operator has a cluster role binding to the role I defined in the chart, and if any other time bindings are present.

I would need to check that in details indeed.

**Comment by chevdor** [comment]
Here is some feedback:
```
k get  clusterrole | grep netchecks
netchecks                                                                2023-11-21T14:33:34Z
netchecks-operator                                                       2023-11-21T08:37:15Z
netchecks-operator-policy-reporter                                       2023-11-21T08:37:15Z
```

```
k get -n $ns serviceaccount           
NAME                SECRETS   AGE
default             0         51d
netcheck-operator   0         19h
```

```
k get  clusterrolebinding | grep netchecks
netchecks                                                             ClusterRole/netchecks                                                                29d
netchecks-operator                                                    ClusterRole/netchecks-operator                                                       30d
netchecks-operator-policy-reporter                                    ClusterRole/netchecks-operator-policy-reporter                                       30d
```

```
k get clusterrolebinding netchecks-operator -o yaml   
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"<...>"}]}
  creationTimestamp: "2023-11-21T08:37:15Z"
  labels:
    app.kubernetes.io/instance: netchecks-operator
    app.kubernetes.io/name: netchecks
    app.kubernetes.io/version: 0.1.1
  name: netchecks-operator
  resourceVersion: "159469406"
  uid: f3ee9d83-7e55-4171-8f16-d9363a6addaa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netchecks-operator
subjects:
- kind: ServiceAccount
  name: netcheck-operator
  namespace: netchecks
```

**Comment by hardbyte** [comment]
Hi @chevdor I haven't been able to replicate this yet. The `netchecks-operator` ClusterRole that should have been created from the helm chart asks for quite broad Pod permissions - [defined here](https://github.com/hardbyte/netchecks/blob/main/operator/charts/netchecks/templates/clusterrole.yaml#L50-L61).

Would you be able to try the latest version and report back?

https://artifacthub.io/packages/helm/netchecks/netchecks/0.1.12

**Comment by chevdor** [comment]
I just upgraded (using helm) and applied the exact same NetworkAssertion.
I triggered the cron manually and shortly after I saw that everything works now and the result nicely shows in the Polikcy Reporter as well. Nice, thanks for the ping !

Would you mind adding a link to what you think could be the fix ? I am closing anyway since the issue is now resolved.
